# apiVersion: v1
# kind: configmap
# matadata:
#   name: backend
#   namespace: expense
# data:
#  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense # if namespace was not provided it will take the default namespace.
  labels: 
     tier: web
     app: frontend
     project: expense
spec:
  replicas: 2
  selector: 
    matchLabels:
       tier: web
       app: frontend
       project: expense
  template: 
    metadata:
      labels:
       tier: web
       app: frontend
       project: expense
    spec:
      containers:
      - name: frontend
        image: raidi/frontend:v1
      
---
apiVersion : v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    tier: web
    app: frontend
    project: expense
  ports:
   - name: frontend-port
     protocol: TCP
     port: 80 # service port
     targetPort: 80 #container port


#ctl get pods -n expense ---> (if -n is not given it will take defacult namespace)