#head-less service .
apiVersion : v1
kind: Service
metadata:
  name: mysql-headless
  namespace: expense
spec:
  clusterIP: None # for headless service there is no cluster ip 
  selector:
    project: expense
    component: mysql
    tier: db
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306 #container port
---
 # normal Service 
apiVersion : v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    selector:
    project: expense
    component: mysql
    tier: db
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306 #container port
---
# statefull-set 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
     project: expense
     component: mysql
     tier: db
  serviceName: "mysql-headless" # this is  headless-service shouid be menction
  replicas: 2 
  template:
    metadata:
      labels:
        project: expense
        component: mysql
        tier: db   
    spec: 
      containers:
      - name: mysql
        image: raidi/mysql:v1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
 
  #This is pvc defination directly menctioned here
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "expense-ebs"
      resources:
        requests:
          storage: 1Gi